### ISSUE TITLE
Error al Implementar el paquete lowdb

### ISSUE THREAD

**Issue by alu0101328447** [ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z#1]
Al intentar implementar el paquete lowdb en la clase [musicDataBase](https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z/blob/master/src/musicDataBase.ts), cuando estamos realizando las pruebas en el archivo [test.spec.ts](https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z/blob/master/test/test.spec.ts), nos muestra un error por consola sobre ` typerror unknown file extension ts`.

Tras haber investigado, no hemos encontrado una respuesta a este error que lo soluciones y por tanto queríamos preguntarle si sabe qué puede estar pasando.  

 Actualmente tenemos partes de la clase [musicDataBase](https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z/blob/master/src/musicDataBase.ts) comentada, al igual que los [test](https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z/blob/master/test/test.spec.ts) debido a que nos estamos intentando centrar en la solución a este problema. De la misma manera, los test los haremos por separado en un futuro, pero de momento los tenemos en el mismo fichero por comodidad.

@esegredo , @amarrerod.

Muchas gracias
Un saludo

**Comment by esegredo** [comment]
Hola, buenas tardes.

¿Puedes crear un issue concreto en el fichero y línea en la que está surgiendo el problema?

Gracias.
@alu0101328447

**Comment by alu0101328447** [comment]
La línea del archivo [musicDatabase](https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z/blob/master/src/musicDataBase.ts) que nos da problemas es la siguiente: 

https://github.com/ULL-ESIT-INF-DSI-2122/ull-esit-inf-dsi-21-22-prct07-music-datamodel-grupo-z/blob/53478c40eb29bfe625ca991f504b9d37fe01bbc9/src/musicDataBase.ts#L10

**Comment by alu0101326351** [comment]
Ya hemos resuelto el problema, no hace falta que mire este asunto

**Comment by esegredo** [comment]
¿Cuál era el problema finalmente?

Gracias.

**Comment by alu0101326351** [comment]
Que teníamos una versión de lowdb que no era compatible con la documentación que estábamos mirando
